version: "3"
services:
        php:
                build: .
                ports:
                        - "9000:9000"
                volumes:
                        - "/var/www/html:/var/www/html"